apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-yekoywmo
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-yekoywmo:26c5a25abe22980ce04410f9d5e1908151cf2854@sha256:8ca8d8da4b8a4a48dda4065fe0eeaa4555b2c98b81fc8fd35ab684e0e20c57ce
        name: container-image  
